Fix git pre-push hook: display only once for git-log failure

diff --git a/config/git/template/hooks/pre-push b/config/git/template/hooks/pre-push
--- a/config/git/template/hooks/pre-push
+++ b/config/git/template/hooks/pre-push
@@ -61,16 +61,16 @@ while read local_ref local_sha remote_ref remote_sha; do
   log_ret=$?
   if [ "$log_ret" != 0 ]; then
     echo 'ERROR (pre-push hook)!' >&2
-    echo 'git-log failed (non-fast-forward / forced push?)' >&2
+    echo 'git-log failed (non-fast-forward?!)' >&2
     echo "cmd: $log_cmd" >&2
     echo "log: $log" >&2
     ret=1
-  fi
-  if [ -n "$log" ]; then
+
+  elif [ -n "$log" ]; then
     echo 'ERROR (pre-push hook)!' >&2
     echo "There are commits with a bad pattern ($BAD_LOG_PATTERN)!" >&2
     echo "        local_ref: $local_ref => remote_ref: $remote_ref" >&2
-    debug "git-log argument: $log_arg" >&2
+    debug "cmd: $log_cmd" >&2
     echo "$log" | sed 's/^/  /' >&2
     ret=1
   fi
