awesome-restart: write args to file for session runner + minor fixes

diff --git a/usr/bin/awesome-restart b/usr/bin/awesome-restart
--- a/usr/bin/awesome-restart
+++ b/usr/bin/awesome-restart
@@ -5,11 +5,14 @@
 # The session runner is ./usr/bin/session-run-awesome.sh.
 
 awesome_pid=
-for p in $(pgrep awesome); do
-  if grep -q "^DISPLAY=$DISPLAY" /proc/$p/environ; then
+for p in $(pgrep -x awesome); do
+  if grep -q "^DISPLAY=$DISPLAY$" "/proc/$p/environ"; then
     echo "Found pid $p for DISPLAY=$DISPLAY."
+    if [ -n "$awesome_pid" ]; then
+      echo "ERROR: found multiple pids!? ($awesome_pid, $p) - Aborting."
+      exit 1
+    fi
     awesome_pid=$p
-    break
   fi
 done
 [ -z "$awesome_pid" ] && {
@@ -17,7 +20,7 @@ done
   exit 1
 }
 
-session_pid=$(ps -o ppid= $awesome_pid)
+session_pid=$(ps -o ppid= "$awesome_pid")
 [ -z "$session_pid" ] && {
   echo "No session PID found for pid $awesome_pid (DISPLAY=$DISPLAY)." >&2
   exit 1
@@ -25,6 +28,10 @@ session_pid=$(ps -o ppid= $awesome_pid)
 
 # echo "Signalling session (USR1), pid=${session_pid}."
 kill -USR1 "$session_pid"
+
+# Write args to a file that is read by ~/.dotfiles/usr/bin/session-run-awesome.sh.
+args_file="/var/run/user/$(id -u)/awesome-restart-args"
+echo "$@" > $args_file
 
 # echo "Sending TERM to awesome: pid=${awesome_pid}."
 kill -TERM "$awesome_pid"
