dotfiles-encrypt: check for PASSWDFILE.

diff --git a/usr/bin/dotfiles-encrypt b/usr/bin/dotfiles-encrypt
--- a/usr/bin/dotfiles-encrypt
+++ b/usr/bin/dotfiles-encrypt
@@ -4,6 +4,8 @@ set -e
 
 PASSWDFILE=~/.dotfiles/.passwd
 
+test -f $PASSWDFILE || { echo "Missing password file $PASSWDFILE."; exit 1; }
+
 if [ "$(basename $0)" = "dotfiles-encrypt" ]; then
   echo "$@" | openssl enc -aes-256-cbc -a -A -salt -pass file:$PASSWDFILE
 else
