Update theme variant handling

diff --git a/usr/bin/sh-setup-x-theme b/usr/bin/sh-setup-x-theme
--- a/usr/bin/sh-setup-x-theme
+++ b/usr/bin/sh-setup-x-theme
@@ -27,18 +27,24 @@ debug() {
   # echo "$(date +%FT%T) [sh-setup-x-theme:$$:$(ps -o cmd= $$)] $@" >> /tmp/debug-sh-setup-x-theme.log
 }
 
-variant_from_config() {
-  if [ -f $X_THEME_VARIANT_CONFIG_FILE ]; then
-    variant=$(cat $X_THEME_VARIANT_CONFIG_FILE)
-    debug "variant from cfg: $variant"
-  else
-    debug "Config file ($X_THEME_VARIANT_CONFIG_FILE) does not exist."
+get_variant_from_config() {
+  if [ -n "$TMUX" ]; then
+    tmux_variant="$(tmux show-env MY_X_THEME_VARIANT 2>/dev/null | cut -d= -f 2)"
+    config_variant="$tmux_variant"
+    debug "variant from tmux: $config_variant"
   fi
-  if [ -z "$variant" ]; then
-      variant=auto
-      debug "variant from fallback: $variant"
+  if [ -z "$config_variant" ]; then
+    if [ -f $X_THEME_VARIANT_CONFIG_FILE ]; then
+      config_variant=$(cat $X_THEME_VARIANT_CONFIG_FILE)
+      debug "variant from cfg: $config_variant"
+    else
+      debug "Config file ($X_THEME_VARIANT_CONFIG_FILE) does not exist."
+    fi
+    if [ -z "$config_variant" ]; then
+      config_variant=auto
+      debug "variant from fallback: $config_variant"
+    fi
   fi
-  echo "$variant"
 }
 
 # Init once and export the value.
@@ -53,7 +59,12 @@ while [ "${1#-*}" != "$1" ]; do
     -q ) # Query/info.
       echo "Current theme variant: MY_X_THEME_VARIANT=$MY_X_THEME_VARIANT."
       echo "BASE16_THEME: $BASE16_THEME."
-      echo "Theme in config: $(variant_from_config)."
+      get_variant_from_config
+      if [ -n "$tmux_variant" ]; then
+        echo "Theme from tmux: $config_variant."
+      else
+        echo "Theme from config: $config_variant."
+      fi
       echo "Use 'auto', 'dark' or 'light' to change it."
       exit
       ;;
@@ -63,32 +74,29 @@ while [ "${1#-*}" != "$1" ]; do
 done
 
 debug "RUN: $0 $*"
-variant=$1
-debug "Requested variant: $variant"
+given_variant=$1
+debug "Requested variant: $given_variant"
 
 # No argument provided: read config/env.
-if [ -z "$variant" ]; then
-  variant=$(variant_from_config)
-
+if [ -z "$given_variant" ]; then
+  get_variant_from_config
+  given_variant="$config_variant"
+  SAVE_VARIANT=0
 else
   FORCE=1
-  debug "(forced) variant from arg: $variant"
-
   if [ "$SHELL_ONLY" != 1 ]; then
-    # Save given value.
-    case $variant in
-      auto)
-        if [ -f "$X_THEME_VARIANT_CONFIG_FILE" ]; then
-          rm "$X_THEME_VARIANT_CONFIG_FILE"
-        fi
-        ;;
-      light|dark)
-        echo "$1" > "$X_THEME_VARIANT_CONFIG_FILE"
-        echo "Saved variant=$1." >&2 ;;
-      * ) echo "Invalid variant: $variant" >&2; exit 64
-    esac
+    SAVE_VARIANT=1
   fi
 fi
+variant="$given_variant"
+debug "given_variant: $given_variant"
+
+# Refresh terminal stuff (base16, dircolors) in a new urxvt instance.
+TTY="$(tty)"
+if [ "$FORCE" = 1 ] || [ "$_MY_X_THEME_VARIANT_TTY" != "$TTY" ]; then
+  REFRESH_TERM=1
+fi
+echo "export _MY_X_THEME_VARIANT_TTY=\$TTY"
 
 # Get auto-theme from get-daytime-period for "auto",
 # and validate value.
@@ -123,9 +131,8 @@ esac
 #   changed_xrdb=1
 # fi
 
-
 if [ -n "$DISPLAY" ] && [ "$USER" != "root" ] && [ "$SHELL_ONLY" != 1 ] \
-  && hash xrdb 2>/dev/null; then
+  && [ -z "$TMUX" ] && hash xrdb 2>/dev/null; then
   # Query "mythemevariant" resource, used to hold the current state.
   # Unset by default in ~/.Xresources.
   cur_xrdb_theme="$(xrdb -query|sed -n -E -e '/mythemevariant:\t/ {s/.*:\t//p;q}')"
@@ -133,24 +140,8 @@ if [ -n "$DISPLAY" ] && [ "$USER" != "root" ] && [ "$SHELL_ONLY" != 1 ] \
   if [ "$FORCE" = 1 ] || [ "$cur_xrdb_theme" != "$variant" ]; then
     if [ "$variant" = dark ]; then
       xrdb -DSOLARIZED_DARK -I"$HOME" -merge ~/.Xresources
-
-      # Send escape codes for urxvt to change colors.
-      if [ "${TERM#rxvt}" != "$TERM" ] || [ "${COLORTERM#rxvt}" != "$COLORTERM" ]; then
-        # XXX: does not work on first "try".
-        # [ -n "$TMUX" ] && echo "printf '\033Ptmux;\033'"
-        echo "printf '\033]11;#002b36\007\033]10;#839496\007\033]12;#93a1a1\007\033]13;#93a1a1\007\033]708;#002b36\007'"
-        # [ -n "$TMUX" ] && echo "printf '\033\\'"
-      fi
     elif [ "$variant" = light ]; then
       xrdb -DSOLARIZED_LIGHT -I"$HOME" -merge ~/.Xresources
-
-      # Send escape codes for urxvt to change colors.
-      if [ "${TERM#rxvt}" != "$TERM" ] || [ "${COLORTERM#rxvt}" != "$COLORTERM" ]; then
-        # XXX: does not work on first "try".
-        # [ -n "$TMUX" ] && echo "printf '\033Ptmux;\033'"
-        echo "printf '\033]11;#fdf6e3\007\033]10;#657b83\007\033]12;#586e75\007\033]13;#586e75\007\033]708;#fdf6e3\007'"
-        # [ -n "$TMUX" ] && echo "printf '\033\\'"
-      fi
     fi
 
     echo "mythemevariant: $variant" | xrdb -merge
@@ -158,16 +149,11 @@ if [ -n "$DISPLAY" ] && [ "$USER" != "root" ] && [ "$SHELL_ONLY" != 1 ] \
   fi
 fi
 
-if [ "$variant" = "light" ]; then
-  DIRCOLORS_FILE=~/.dotfiles/lib/dircolors-solarized/dircolors.ansi-light
-else
-  # DIRCOLORS_FILE=~/.dotfiles/lib/dircolors-solarized/dircolors.ansi-dark
-  # Prefer LS_COLORS repo, which is more fine-grained, but does not look good on light bg.
-  DIRCOLORS_FILE=~/.dotfiles/lib/LS_COLORS/LS_COLORS
-fi
+DIRCOLORS_FILE=~/.dotfiles/lib/LS_COLORS/LS_COLORS
 
 # Setup dircolors once.
-if [ "$FORCE" = 1 ] || [ "$DIRCOLORS_SETUP" != "$DIRCOLORS_FILE" ]; then
+if [ -n "$DIRCOLORS_FILE" ] \
+    && ([ "$REFRESH_TERM" = 1 ] || [ "$DIRCOLORS_SETUP" != "$DIRCOLORS_FILE" ]); then
   debug "Setting up DIRCOLORS_FILE=$DIRCOLORS_FILE"
   debug "DIRCOLORS_SETUP=$DIRCOLORS_SETUP"
   if [ -n "$DIRCOLORS_SETUP" ]; then
@@ -178,143 +164,105 @@ if [ "$FORCE" = 1 ] || [ "$DIRCOLORS_SETUP" != "$DIRCOLORS_FILE" ]; then
 
   # debug "running: dircolors -b $DIRCOLORS_FILE"
   echo "$(dircolors -b $DIRCOLORS_FILE);"
-  echo "export DIRCOLORS_SETUP=$DIRCOLORS_FILE;"
+  echo "export DIRCOLORS_SETUP=$DIRCOLORS_FILE"
 fi
 
 # Used in ~/.vimrc.
 echo "export MY_X_THEME_VARIANT=$variant;"
 
-# Update tmux env.
-if [ -n "$TMUX" ] && [ "$SHELL_ONLY" != 1 ]; then
-  debug "Updating tmux env.."
-  COLORS=$(tput colors)
-  debug "Colors: $COLORS"
-  if [ "$COLORS" -lt 16 ]; then
-    debug "SKIP: not enough colors ($COLORS are available (via 'tput colors'); TERM=$TERM)."
+# Configure colors for fzf.
+if hash fzf >/dev/null; then
+  if [ -z "$_FZF_DEFAULT_OPTS_BASE" ]; then
+    echo "export _FZF_DEFAULT_OPTS_BASE=\"\$FZF_DEFAULT_OPTS\""
+  fi
+  [ $variant = "light" ] && bg=21 || bg=18
+  echo "export FZF_DEFAULT_OPTS='$_FZF_DEFAULT_OPTS_BASE --color 16,bg+:$bg'"
+fi
 
-  elif [ -n "$_tmux_conf" ] \
-      && [ "$(tmux show-env MY_X_THEME_VARIANT 2>/dev/null)" != "MY_X_THEME_VARIANT=$variant" ]; then
-    echo "tmux set-environment MY_X_THEME_VARIANT $variant \; \
-      source-file $_tmux_conf \; \
-      display 'Reloaded tmux for $variant theme variant.'"
+# Update tmux env, after sending escape codes eventually, which the
+# "tmux display" might prevent to work correctly (?!).  (might be obsolete)
+# This also inits it initially.
+if [ -n "$TMUX" ]; then  # && [ "$SHELL_ONLY" != 1 ]; then
+  COLORS="$(tput colors)"
+  if [ "$COLORS" -lt 16 ]; then
+    debug "SKIP tmux: not enough colors ($COLORS are available (via 'tput colors'); TERM=$TERM)."
+  else
+    debug "tmux_variant: $tmux_variant"
+    tmux_tmp_conf="$(mktemp)"
+    if [ -z "$tmux_variant" ]; then
+      echo "echo 'theme-variant: setting tmux env: $variant.'"
+
+      tmux_session="$(tmux display-message -p '#S')"
+      tmux_windows=
+      for w in $(tmux list-windows -t "$tmux_session" -F '#{window_id}'); do
+        sed -n "s/ -g//; /^set /p; /^if/p; s/^\s*setw /\0-t $w /p" "$HOME/.dotfiles/lib/tmux-colors-solarized/tmuxcolors-$variant.conf" >> "$tmux_tmp_conf"
+      done
+    else
+      # echo "echo 'theme-variant: styling new tmux window ($variant).'"
+      tmux_windows=""
+      sed -n "s/ -g//; /^set /p; /^if/p; s/^\s*setw /\0$tmux_windows/p" "$HOME/.dotfiles/lib/tmux-colors-solarized/tmuxcolors-$variant.conf" > "$tmux_tmp_conf"
+    fi
+
+    echo "tmux set-env MY_X_THEME_VARIANT $variant"
+    echo "tmux source $tmux_tmp_conf"
+    echo "rm '$tmux_tmp_conf'"
   fi
 fi
 
-if [ "$MY_X_THEME_VARIANT" != "$variant" ] \
-  || [ "${BASE16_THEME##*.}" != "$variant" ]; then
-  # Setup base16-shell.
+# Setup base16-shell.
+if [ "$REFRESH_TERM" = 1 ] || [ "${BASE16_THEME##*.}" != "$variant" ]; then
   if [ "${TERM%%-*}" = 'linux' ]; then
     echo "Skipping base16-shell with TERM=linux." >&2
   else
-    BASE16_SHELL_DIR=~/.dotfiles/lib/base16/base16-shell
-    if [ -d "$BASE16_SHELL_DIR" ]; then
-      echo "export BASE16_THEME=solarized.$variant"
-      base16_scheme_file=$BASE16_SHELL_DIR/base16-solarized.${variant}.sh
-      [ -s $base16_scheme_file ] && echo "source $base16_scheme_file" || {
-        echo "$base16_scheme_file does not exist." >&2
-      }
-    fi
-
-    if [ -n "$MY_X_THEME_VARIANT" ]; then
-      # Reload ZSH theme conditionally.
-      echo "sh-setup-x-theme: reloading zsh.." >&2
-      echo "command -v reloadzsh > /dev/null && reloadzsh"
-    fi
-
-    if hash fzf >/dev/null; then
-      if [ -z "$_FZF_DEFAULT_OPTS_BASE" ]; then
-        # shellcheck disable=SC2016
-        echo 'export _FZF_DEFAULT_OPTS_BASE="$FZF_DEFAULT_OPTS"'
-      fi
-      if [ $variant = "light" ]; then
-        echo "export FZF_DEFAULT_OPTS='$_FZF_DEFAULT_OPTS_BASE --color 16,bg+:21'"
-      else
-        echo "export FZF_DEFAULT_OPTS='$_FZF_DEFAULT_OPTS_BASE --color 16,bg+:18'"
-      fi
+    echo "base16_theme solarized.$variant"
+    if [ -n "$TMUX" ]; then
+      # shellcheck disable=SC2016
+      echo 'tmux set-environment BASE16_THEME "$BASE16_THEME"'
     fi
   fi
 fi
 
-    # # Setup/change xrdb / gnome-terminal profile. {{{
-    # if [[ "$MY_X_THEME_VARIANT" != "$variant" ]]; then
-    #     if [[ -n $commands[xrdb] ]]; then
-    #         local curbg changed_xrdb
-    #         cur_xrdb_theme="$(xrdb -query|sed -n -E -e '/mythemevariant:\t/ {s/.*:\t//p;q}')"
-    #
-    #         if [[ $cur_xrdb_theme != $variant ]]; then
-    #             if [[ $variant == dark ]]; then
-    #                 xrdb -DSOLARIZED_DARK ~/.Xresources
-    #             else
-    #                 xrdb -DSOLARIZED_LIGHT ~/.Xresources
-    #             fi
-    #         fi
-    #         # curbg="$(xrdb -query|sed -n -e '/^\*background:/ {p;q}' | tr -d '[:space:]' | cut -f2 -d:)"
-    #         # if [[ $curbg == '#fdf6e3' ]]; then
-    #         #     if [[ $variant == "dark" ]]; then
-    #         #         # xrdb -DSOLARIZED_DARK ~/.Xresources
-    #         #         xrdb -merge ~/.dotfiles/lib/solarized-xresources/Xresources.dark
-    #         #         changed_xrdb=1
-    #         #     fi
-    #         # elif [[ $variant == "light" ]]; then
-    #         #     # xrdb -DSOLARIZED_LIGHT ~/.Xresources
-    #         #     xrdb -merge ~/.dotfiles/lib/solarized-xresources/Xresources.light
-    #         #     changed_xrdb=1
-    #         # fi
-    #
-    #         if [[ $changed_xrdb == 1 ]]; then
-    #             echo "Changed xrdb theme to $variant (curbg: $curbg; variant=$variant)."
-    #         fi
-    #     fi
-    #     if is_gnome_terminal; then
-    #         local wanted_gnome_terminal_profile="Solarized-$variant"
-    #         # local id_light=e6e34acf-124a-43bd-ad32-46fb0765ad76
-    #         # local id_dark=b1dcc9dd-5262-4d8d-a863-c897e6d979b9
-    #
-    #         local default_profile_id=${$(dconf read /org/gnome/terminal/legacy/profiles:/default)//\'/}
-    #         # echo "default_profile_id:$default_profile_id"
-    #         local default_profile_name=${$(dconf read /org/gnome/terminal/legacy/profiles:/":"$default_profile_id/visible-name)//\'/}
-    #         # echo "default_profile_name:$default_profile_name"
-    #
-    #         # local -h cur_profile=$(gconftool-2 --get /apps/gnome-terminal/global/default_profile)
-    #         if [[ $default_profile_name != $wanted_gnome_terminal_profile ]]; then
-    #             # Get ID of wanted profile.
-    #
-    #             wanted_gnome_terminal_profile_id=$(
-    #                 dconf dump "/org/gnome/terminal/legacy/profiles:/" \
-    #                 | grep -P "^(visible-name='$wanted_gnome_terminal_profile'|\[:)" \
-    #                 | grep '^visible-name' -B1 | head -n1 \
-    #                 | sed -e 's/^\[://' -e 's/]$//')
-    #
-    #             echo "Changing gnome-terminal default profile to: $wanted_gnome_terminal_profile ($wanted_gnome_terminal_profile_id)."
-    #             # gconftool-2 --set --type string /apps/gnome-terminal/global/default_profile $gnome_terminal_profile
-    #             dconf write /org/gnome/terminal/legacy/profiles:/default "'$wanted_gnome_terminal_profile_id'"
-    #         fi
-    #     fi
-    # fi  # }}}
+if [ "$MY_X_THEME_VARIANT" != "$variant" ] || [ "$FORCE" = 1 ]; then
+  if [ "${COLORTERM#rxvt}" != "$COLORTERM" ]; then
+    if [ "$variant" = light ]; then
+      escape_codes='\033]11;#fdf6e3\007 \033]10;#657b83\007 \033]12;#586e75\007 \033]13;#586e75\007 \033]708;#fdf6e3\007 \033]709;#fdf6e3\007'
+    else
+      escape_codes='\033]11;#002b36\007 \033]10;#839496\007 \033]12;#93a1a1\007 \033]13;#93a1a1\007 \033]708;#002b36\007 \033]709;#657b83\007'
+    fi
+    cat <<EOF
+    _printf_for_tmux() {
+      local i="\$1"
+      if [ -n "\$TMUX" ]; then
+        i="\\ePtmux;\\e\$i\\e\\\\"
+      fi
+      printf '%b' "\$i"
+    }
+EOF
+    for i in $escape_codes; do
+      echo "_printf_for_tmux '$i'"
+    done
+  fi
+fi
 
-    # Could adjust current urxvt; but this can be done using ctrl-alt-9/0.
-    # # URxvt.keysym.M-C-0: command:\033]11;S_base3\007\033]10;S_base00\007\033]12;S_base01\007\033]13;S_base01\007\033]708;S_base3\007
-    # # URxvt.keysym.M-C-9: command:\033]11;S_base03\007\033]10;S_base0\007\033]12;S_base1\007\033]13;S_base1\007\033]708;S_base03\007
-    # my-send-term-escape '\e]11; \007'
-
-    # my-send-term-escape() {
-    #     # Wrap escape code for tmux.
-    #     [[ -n $TMUX ]] && printf '\ePtmux;\e'
-    #
-    #     echo -ne $1
-    #
-    #     # End escape code wrapping for tmux.
-    #     [[ -n $TMUX ]] && printf '\e\\'
-    # }
-
-
-# # Init once and export the value.
-# # This gets used in Vim to auto-set the background, too.
-# if [ -z "$MY_X_THEME_VARIANT" ]; then
-#     if [ -f "$X_THEME_VARIANT_CONFIG_FILE" ]; then
-#         MY_X_THEME_VARIANT=$(<$X_THEME_VARIANT_CONFIG_FILE)
-#     else
-#         MY_X_THEME_VARIANT=auto
-#     fi
-#     theme_variant $MY_X_THEME_VARIANT
-# fi
+if [ "$SAVE_VARIANT" = 1 ]; then
+  # Save given value.
+  case $variant in
+    auto)
+      if [ -n "$TMUX" ]; then
+        tmux set-env -u MY_X_THEME_VARIANT
+      elif [ -f "$X_THEME_VARIANT_CONFIG_FILE" ]; then
+        rm "$X_THEME_VARIANT_CONFIG_FILE"
+      fi
+      ;;
+    light|dark)
+      if [ -n "$TMUX" ]; then
+        tmux set-env MY_X_THEME_VARIANT "$variant"
+        echo "Saved variant=$1 in tmux." >&2
+      else
+        echo "$1" > "$X_THEME_VARIANT_CONFIG_FILE"
+        echo "Saved variant=$1." >&2
+      fi
+      ;;
+    * ) echo "Invalid variant: $variant" >&2; exit 64
+  esac
+fi
